// flows/receipt/screens/ConfirmationScreen.tsx
import React, { useEffect, useMemo, useCallback, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Linking,
} from 'react-native';
import { useNavigation, CommonActions } from '@react-navigation/native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
  CheckCircleIcon,
  PaperPlaneTiltIcon,
  BellIcon,
  NoteIcon,
  ArrowCounterClockwiseIcon,
  PlusIcon,
  BankIcon,
  MoneyIcon,
} from 'phosphor-react-native';

import {
  useTheme,
  useAppDispatch,
  useAppSelector,
} from '../../../../store/hooks';
import ActionButton from '../../../../components/common/ActionButton';
import {
  selectReceiptCustomer,
  selectReceiptAmount,
  selectRemainingAfterPayment,
  selectReceiptPaymentMethod,
  selectInvoiceAllocations,
  selectAllocationSummary,
  selectReceiptsLoading,
  selectReceiptsError,
  selectPaymentResponse,
  submitReceiptPayment,
  resetReceiptsFlow,
} from '../../../../store/slices/receiptsSlice';
import Toast from 'react-native-toast-message';

const ConfirmationScreen: React.FC = () => {
  const theme = useTheme();
  const navigation = useNavigation();
  const dispatch = useAppDispatch();

  // Redux selectors
  const customer = useAppSelector(selectReceiptCustomer);
  const amount = useAppSelector(selectReceiptAmount);
  const remainingAfterPayment = useAppSelector(selectRemainingAfterPayment);
  const paymentMethod = useAppSelector(selectReceiptPaymentMethod);
  const invoiceAllocations = useAppSelector(selectInvoiceAllocations);
  const allocationSummary = useAppSelector(selectAllocationSummary);
  const isLoading = useAppSelector(selectReceiptsLoading);
  const error = useAppSelector(selectReceiptsError);
  const paymentResponse = useAppSelector(selectPaymentResponse);
  const [isRedirect, setRedirect] = useState<boolean>(false);
  const styles = useMemo(() => createStyles(theme), [theme]);
  console.log(remainingAfterPayment);
  // Submit payment on mount
  useEffect(() => {
    if (!paymentResponse && !isLoading && !error && !isRedirect) {
      dispatch(submitReceiptPayment());
    }
  }, [dispatch, paymentResponse, isLoading, error, isRedirect]);

  console.log(paymentMethod);
  // Get payment method label
  const getPaymentMethodLabel = useCallback(() => {
    switch (paymentMethod) {
      case 'Cash':
        return 'Cash';
      case 'Bank':
        return 'Bank Transfer';
      default:
        return paymentMethod || 'Unknown';
    }
  }, [paymentMethod]);

  // Get payment method icon
  const PaymentMethodIcon = useMemo(() => {
    return paymentMethod === 'Bank' ? BankIcon : MoneyIcon;
  }, [paymentMethod]);

  const handleDone = useCallback(() => {
    setRedirect(true);
    dispatch(resetReceiptsFlow());
    // Reset to home/dashboard
    navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: 'Home' as never }],
      }),
    );
  }, [dispatch, navigation]);

  const handleUndo = useCallback(() => {
    // TODO: Implement undo functionality with API
    dispatch(resetReceiptsFlow());
    navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: 'Dashboard' as never }],
      }),
    );
  }, [dispatch, navigation]);

  const handleAddAnother = useCallback(() => {
    setRedirect(true);
    dispatch(resetReceiptsFlow());
    // Navigate back to customer selection
    navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: 'CustomerSelection' as never }],
      }),
    );
  }, [dispatch, navigation]);

  const handleSendReceipt = useCallback(() => {
    if (customer?.phoneNumber) {
      const message =
        `📒 Payment Recived - ${customer?.name}\n\n` +
        `Amount Recieved: Rs. ${amount?.toLocaleString() || 0}\n` +
        `Payment Method: ${getPaymentMethodLabel()}\n` +
        `Date: ${new Date().toLocaleDateString('en-US', {
          month: 'long',
          day: 'numeric',
          year: 'numeric',
        })}\n\n` +
        `Generated by HisabKaro`;
      // Clean the phone number and format for WhatsApp
      const cleanPhone = customer.phoneNumber.replace(/\D/g, '');
      Linking.openURL(
        `whatsapp://send?phone=${cleanPhone}&text=${encodeURIComponent(
          message,
        )}`,
      );
    } else {
      Toast.show({
        type: 'info',
        text1: 'No Phone',
        text2: 'No phone number available for this customer',
      });
    }
    // TODO: Implement send receipt functionality
    console.log('Send receipt to', customer?.name);
  }, [customer]);

  const handleSetReminder = useCallback(() => {
    // TODO: Implement reminder functionality
    console.log('Set reminder for', customer?.name);
  }, [customer]);

  const handleAddNote = useCallback(() => {
    // TODO: Implement add note functionality
    console.log('Add note');
  }, []);

  // Loading state
  if (isLoading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={theme.colors.primary} />
          <Text style={styles.loadingText}>Recording payment...</Text>
        </View>
      </SafeAreaView>
    );
  }

  // Error state
  if (error && !paymentResponse) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.errorContainer}>
          <Text style={styles.errorTitle}>Payment Failed</Text>
          <Text style={styles.errorMessage}>{error}</Text>
          <ActionButton
            title="Try Again"
            onPress={() => dispatch(submitReceiptPayment())}
            variant="primary"
          />
          <TouchableOpacity
            style={styles.errorBackButton}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.errorBackText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        {/* Success Header */}
        <View style={styles.successHeader}>
          <View style={styles.successIconContainer}>
            <CheckCircleIcon
              size={64}
              color={theme.colors.success}
              weight="fill"
            />
          </View>
          <Text style={styles.successTitle}>Payment Recorded</Text>
          <Text style={styles.successSubtitle}>
            Receipt created successfully
          </Text>
        </View>

        {/* Summary Card */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Customer</Text>
            <Text style={styles.summaryValue}>{customer?.name || 'N/A'}</Text>
          </View>

          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Amount Received</Text>
            <Text style={[styles.summaryValue, styles.summaryValueLarge]}>
              PKR {amount.toLocaleString()}
            </Text>
          </View>

          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Payment Method</Text>
            <View style={styles.paymentMethodValue}>
              <PaymentMethodIcon
                size={16}
                color={theme.colors.text.secondary}
              />
              <Text>{getPaymentMethodLabel()}</Text>
            </View>
          </View>

          {/* Show allocated invoices count */}
          {invoiceAllocations.length > 0 && (
            <View style={styles.summaryRow}>
              <Text style={styles.summaryLabel}>Invoices Allocated</Text>
              <Text style={styles.summaryValue}>
                {invoiceAllocations.length} invoice
                {invoiceAllocations.length > 1 ? 's' : ''}
              </Text>
            </View>
          )}

          {/* Unallocated amount (advance) */}
          {allocationSummary.unallocatedAmount > 0 && (
            <View style={styles.summaryRow}>
              <Text style={styles.summaryLabel}>Advance Payment</Text>
              <Text style={[styles.summaryValue, styles.advanceValue]}>
                PKR {allocationSummary.unallocatedAmount.toLocaleString()}
              </Text>
            </View>
          )}

          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Date</Text>
            <Text style={styles.summaryValue}>
              {new Date().toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </Text>
          </View>

          <View style={styles.divider} />

          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Remaining Balance</Text>
            <Text
              style={[
                styles.summaryValue,
                styles.summaryValueBold,
                {
                  color:
                    remainingAfterPayment > 0
                      ? theme.colors.warning
                      : remainingAfterPayment === 0
                      ? theme.colors.success
                      : theme.colors.info,
                },
              ]}
            >
              PKR {Math.abs(remainingAfterPayment).toLocaleString()}
              {remainingAfterPayment < 0 && ' (Credit)'}
            </Text>
          </View>
        </View>

        {/* Actions Section */}
        <Text style={styles.actionsTitle}>What's next?</Text>

        <TouchableOpacity
          style={styles.actionCard}
          onPress={handleSendReceipt}
          activeOpacity={0.7}
        >
          <View style={[styles.actionIcon, { backgroundColor: '#007AFF15' }]}>
            <PaperPlaneTiltIcon size={24} color="#007AFF" weight="fill" />
          </View>
          <View style={styles.actionContent}>
            <Text style={styles.actionLabel}>
              Send Receipt to {customer?.name || 'Customer'}
            </Text>
            <Text style={styles.actionDescription}>WhatsApp / SMS / Email</Text>
          </View>
        </TouchableOpacity>

        {remainingAfterPayment > 0 && (
          <TouchableOpacity
            style={styles.actionCard}
            onPress={handleSetReminder}
            activeOpacity={0.7}
          >
            <View style={[styles.actionIcon, { backgroundColor: '#FF950015' }]}>
              <BellIcon size={24} color="#FF9500" weight="fill" />
            </View>
            <View style={styles.actionContent}>
              <Text style={styles.actionLabel}>
                Remind {customer?.name || 'Customer'} for remaining
              </Text>
              <Text style={styles.actionDescription}>
                Set reminder for PKR {remainingAfterPayment.toLocaleString()}
              </Text>
            </View>
          </TouchableOpacity>
        )}

        {/* <TouchableOpacity
          style={styles.actionCard}
          onPress={handleAddNote}
          activeOpacity={0.7}
        >
          <View style={[styles.actionIcon, { backgroundColor: '#5856D615' }]}>
            <NoteIcon size={24} color="#5856D6" weight="fill" />
          </View>
          <View style={styles.actionContent}>
            <Text style={styles.actionLabel}>Add Note</Text>
            <Text style={styles.actionDescription}>Optional memo</Text>
          </View>
        </TouchableOpacity> */}
      </ScrollView>

      {/* Bottom Actions */}
      <View style={styles.bottomActions}>
        <ActionButton title="Done" onPress={handleDone} variant="primary" />

        <View style={styles.secondaryActions}>
          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={handleAddAnother}
          >
            <PlusIcon size={18} color={theme.colors.text.secondary} />
            <Text style={styles.secondaryButtonText}>Add Another</Text>
          </TouchableOpacity>
        </View>
      </View>
    </SafeAreaView>
  );
};

const createStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      padding: theme.spacing.md,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: theme.spacing.md,
    },
    loadingText: {
      fontSize: 16,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.md,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.spacing.xl,
    },
    errorTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: theme.colors.error,
      marginBottom: theme.spacing.sm,
    },
    errorMessage: {
      fontSize: 14,
      color: theme.colors.text.secondary,
      textAlign: 'center',
      marginBottom: theme.spacing.lg,
    },
    errorBackButton: {
      marginTop: theme.spacing.md,
      padding: theme.spacing.sm,
    },
    errorBackText: {
      fontSize: 14,
      color: theme.colors.primary,
    },
    successHeader: {
      alignItems: 'center',
      marginBottom: theme.spacing.lg,
    },
    successIconContainer: {
      marginBottom: theme.spacing.sm,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.colors.text.primary,
      marginTop: theme.spacing.sm,
    },
    successSubtitle: {
      fontSize: 14,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
    },
    summaryCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.lg,
      ...theme.shadows.sm,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: theme.spacing.sm,
    },
    summaryLabel: {
      fontSize: 14,
      color: theme.colors.text.secondary,
    },
    summaryValue: {
      fontSize: 14,
      color: theme.colors.text.primary,
      textAlign: 'right',
      flex: 1,
      marginLeft: theme.spacing.sm,
    },
    summaryValueLarge: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    summaryValueBold: {
      fontWeight: '700',
    },
    advanceValue: {
      color: theme.colors.info,
    },
    paymentMethodValue: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.divider,
      marginVertical: theme.spacing.sm,
    },
    actionsTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.text.primary,
      marginBottom: theme.spacing.md,
    },
    actionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.sm,
      ...theme.shadows.sm,
    },
    actionIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing.md,
    },
    actionContent: {
      flex: 1,
    },
    actionLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
      marginBottom: 2,
    },
    actionDescription: {
      fontSize: 12,
      color: theme.colors.text.secondary,
    },
    bottomActions: {
      padding: theme.spacing.md,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      gap: theme.spacing.sm,
    },
    secondaryActions: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    secondaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.xs,
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.borderRadius.md,
      paddingVertical: theme.spacing.sm,
    },
    secondaryButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.text.secondary,
    },
  });

export default ConfirmationScreen;
