export const ROUTES = {
  SPLASH: 'Splash',
  SPLASH2: 'Splash2',
  SPLASH3: 'Splash3',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  ANALYTICS: 'Analytics',
  TRANSCATIONS: 'Transactions',
  ADD_TRANSACTION_SALES: 'Sales',
  ADD_TRANSACTION_RECEIPT: 'Receipt',
  ADD_TRANSACTION_PURCHASE: 'Purchases',
  ADD_TRANSACTION_EXPENSE: 'Expense',
  ADD_TRANSACTION_BANK: 'Bank',
  ADD_TRANSACTION_SUPPLIER_PAYMENT: 'SupplierPayment',
  ADD_TRANSACTION_ACCOUNT_TRANSFER: 'AccountTransfer',
  TRANSACTION_LIST: 'TransactionList',
  TRANSCATION_DETAIL: 'TransactionDetail',
  TRANSACTION_FILTER: 'TransactionFilter',
  TRANSACTION_SEARCH: 'TransactionSearch',
  TRANSACTION_STATS: 'TransactionStats',
  AI_ASSISTANT: 'AIAssistant',
  AI_CHAT: 'AIChat',
  MENU: 'Menu',
  PROFILE: 'Profile',
  BIOMETRIC_VERIFICATION: 'BiometricVerification',
  STATISTICS: 'Statistics',
  BALANCE_ACCOUNTS: 'BalanceAccounts',
  TRANSACTION_HISTORY: 'TransactionHistory',
  BUDGET: 'Budget',
  EXPENSES: 'Expenses',
  SCHEDULED_PAYMENTS: 'ScheduledPayments',
  NOTIFICATIONS: 'Notifications',
  BANK_ACCOUNT_DETAILS: 'BankAccountDetails',
  EDIT_TRANSACTION: 'EditTransaction',
  EDIT_TRANSACTION_SELECT_PARTY: 'SelectParty',
  EDIT_TRANSACTION_CONFIRM: 'EditConfirmation',
  EDIT_TRANSACTION_HISTORY: 'EditHistory',
  EDIT_TRANSACTION_FLOW: 'EditTransactionFlow',
  EDIT_TRANSACTION_SELECT_CATEGORY: 'SelectCategory',
  EDIT_TRANSACTION_SELECT_ITEM: 'SelectItems',
} as const;

export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
