export const ROUTES = {
  SPLASH: 'Splash',
  SPLASH2: 'Splash2',
  SPLASH3: 'Splash3',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  ANALYTICS: 'Analytics',
  TRANSCATIONS: 'Transactions',
  ADD_TRANSACTION_SALES: 'Sales',
  ADD_TRANSACTION_RECEIPT: 'Receipt',
  ADD_TRANSACTION_PURCHASE: 'Purchases',
  ADD_TRANSACTION_EXPENSE: 'Expense',
  ADD_TRANSACTION_BANK: 'Bank',
  ADD_TRANSACTION_SUPPLIER_PAYMENT: 'SupplierPayment',
  ADD_TRANSACTION_ACCOUNT_TRANSFER: 'AccountTransfer',
  TRANSACTION_LIST: 'TransactionList',
  TRANSCATION_DETAIL: 'TransactionDetail',
  TRANSACTION_FILTER: 'TransactionFilter',
  TRANSACTION_SEARCH: 'TransactionSearch',
  TRANSACTION_STATS: 'TransactionStats',
  AI_ASSISTANT: 'AIAssistant',
  AI_CHAT: 'AIChat',
  MENU: 'Menu',
  DIRECTORY: 'DirectoryTab',
  PROFILE: 'Profile',
  BIOMETRIC_VERIFICATION: 'BiometricVerification',
  STATISTICS: 'Statistics',
  BALANCE_ACCOUNTS: 'BalanceAccounts',
  TRANSACTION_HISTORY: 'TransactionHistory',
  BUDGET: 'Budget',
  EXPENSES: 'Expenses',
  SCHEDULED_PAYMENTS: 'ScheduledPayments',
  NOTIFICATIONS: 'Notifications',
  BANK_ACCOUNT_DETAILS: 'BankAccountDetails',
  EDIT_TRANSACTION: 'EditTransaction',
  EDIT_TRANSACTION_SELECT_PARTY: 'SelectParty',
  EDIT_TRANSACTION_CONFIRM: 'EditConfirmation',
  EDIT_TRANSACTION_HISTORY: 'EditHistory',
  EDIT_TRANSACTION_FLOW: 'EditTransactionFlow',
  EDIT_TRANSACTION_SELECT_CATEGORY: 'SelectCategory',
  EDIT_TRANSACTION_SELECT_ITEM: 'SelectItems',
  // Payments Flow
  PAYMENTS_FLOW: 'PaymentsFlow',
  SELECT_CUSTOMER: 'SelectCustomer',
  SELECT_SUPPLIER: 'SelectSupplier',
  MAKE_PAYMENT: 'MakePayment',
  PAYMENT_SUCCESS: 'PaymentSuccess',
  // Customer Screens
  CUSTOMERS_LIST: 'CustomersList',
  CUSTOMER_DETAIL: 'CustomerDetail',
  CUSTOMER_LEDGER: 'CustomerLedger',
  ADD_CUSTOMER: 'AddCustomer',
  EDIT_CUSTOMER: 'EditCustomer',
  // Supplier Screens
  SUPPLIERS_LIST: 'SuppliersList',
  SUPPLIER_DETAIL: 'SupplierDetail',
  SUPPLIER_LEDGER: 'SupplierLedger',
  ADD_SUPPLIER: 'AddSupplier',
  EDIT_SUPPLIER: 'EditSupplier',
  // Inventory Screens
  INVENTORY_LIST: 'InventoryList',
  PRODUCT_DETAIL: 'ProductDetail',
  ADD_PRODUCT: 'AddProduct',
  EDIT_PRODUCT: 'EditProduct',
  // Bank Accounts Screens
  BANK_ACCOUNTS_LIST: 'BankAccountsList',
  BANK_ACCOUNT_DETAIL: 'BankAccountDetail',
  ADD_BANK_ACCOUNT: 'AddBankAccount',
  EDIT_BANK_ACCOUNT: 'EditBankAccount',

  ADD_JOURNAL_ENTRY: 'AddJournalEntry',

  // Transaction Listing Screens (Directory)
  SALES_INVOICE_LIST: 'SalesInvoiceList',
  SALES_INVOICE_DETAIL: 'SalesInvoiceDetail',
  PURCHASE_INVOICE_LIST: 'PurchaseInvoiceList',
  PURCHASE_INVOICE_DETAIL: 'PurchaseInvoiceDetail',
  PAYMENTS_LIST: 'PaymentsList',
  PAYMENT_DETAIL: 'PaymentDetail',

  // Report Screens
  GENERAL_JOURNAL: 'GeneralJournal',
  GENERAL_LEDGER: 'GeneralLedger',
  PROFIT_LOSS: 'ProfitLoss',
  TRIAL_BALANCE: 'TrialBalance',
  BALANCE_SHEET: 'BalanceSheet',
} as const;

export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
