export const ROUTES = {
  SPLASH: 'Splash',
  SPLASH2: 'Splash2',
  SPLASH3: 'Splash3',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  ANALYTICS: 'Analytics',
  ADD_TRANSACTION: 'AddTransaction',
  ADD_TRANSACTION_MANUAL: 'AddTransactionManual',
  AI_ASSISTANT: 'AIAssistant',
  AI_CHAT: 'AIChat',
  MENU: 'Menu',
  PROFILE: 'Profile',
  BIOMETRIC_VERIFICATION: 'BiometricVerification',
  STATISTICS: 'Statistics',
  BALANCE_ACCOUNTS: 'BalanceAccounts',
  TRANSACTION_HISTORY: 'TransactionHistory',
  BUDGET: 'Budget',
  EXPENSES: 'Expenses',
  SCHEDULED_PAYMENTS: 'ScheduledPayments',
  NOTIFICATIONS: 'Notifications',
  BANK_ACCOUNT_DETAILS: 'BankAccountDetails',
} as const;

export type RouteName = (typeof ROUTES)[keyof typeof ROUTES];
