import React, { useMemo, useState, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  TouchableOpacity,
  Pressable,
  Alert,
  Share,
} from 'react-native';
import {
  XIcon,
  WhatsappLogoIcon,
  FilePdfIcon,
  FileXlsIcon,
  EnvelopeIcon,
  ShareNetworkIcon,
  DotsThreeIcon,
} from 'phosphor-react-native';
import { useTheme } from '../../../store/hooks';

interface ExportReportModalProps {
  visible: boolean;
  onClose: () => void;
  reportTitle: string;
  reportDateRange: string;
  onExportPDF?: () => Promise<void>;
  onExportExcel?: () => Promise<void>;
  onShareWhatsApp?: () => Promise<void>;
  onShareEmail?: () => Promise<void>;
}

type LanguageOption = 'english' | 'romanUrdu';

const ExportReportModal: React.FC<ExportReportModalProps> = ({
  visible,
  onClose,
  reportTitle,
  reportDateRange,
  onExportPDF,
  onExportExcel,
  onShareWhatsApp,
  onShareEmail,
}) => {
  const theme = useTheme();
  const styles = useMemo(() => createStyles(theme), [theme]);

  const [language, setLanguage] = useState<LanguageOption>('english');
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = useCallback(
    async (exportFn?: () => Promise<void>, type: string) => {
      if (!exportFn) {
        Alert.alert('Coming Soon', `${type} export will be available soon!`);
        return;
      }

      try {
        setIsExporting(true);
        await exportFn();
      } catch (error: any) {
        Alert.alert('Error', error.message || `Failed to export ${type}`);
      } finally {
        setIsExporting(false);
      }
    },
    []
  );

  const handleMoreSharing = useCallback(async () => {
    try {
      await Share.share({
        message: `${reportTitle} Report\nPeriod: ${reportDateRange}\n\nGenerated by Hisab Karo`,
        title: reportTitle,
      });
    } catch (error: any) {
      if (error.message !== 'User cancelled') {
        Alert.alert('Error', 'Failed to share report');
      }
    }
  }, [reportTitle, reportDateRange]);

  return (
    <Modal
      visible={visible}
      animationType="slide"
      transparent
      onRequestClose={onClose}
    >
      <Pressable style={styles.overlay} onPress={onClose}>
        <Pressable style={styles.container} onPress={(e) => e.stopPropagation()}>
          {/* Handle Bar */}
          <View style={styles.handleBar} />

          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <XIcon size={24} color={theme.colors.text.secondary} />
            </TouchableOpacity>
            <Text style={styles.headerTitle}>Export Report</Text>
            <TouchableOpacity style={styles.moreButton}>
              <DotsThreeIcon size={24} color={theme.colors.text.secondary} />
            </TouchableOpacity>
          </View>

          {/* Report Preview Card */}
          <View style={styles.previewCard}>
            <View style={styles.previewInfo}>
              <Text style={styles.previewLabel}>REPORT PREVIEW</Text>
              <Text style={styles.previewTitle}>{reportTitle}</Text>
              <Text style={styles.previewDate}>{reportDateRange}</Text>
            </View>
            <View style={styles.previewPlaceholder}>
              <View style={styles.previewLine} />
              <View style={[styles.previewLine, { width: '60%' }]} />
              <View style={[styles.previewLine, { width: '80%' }]} />
            </View>
          </View>

          {/* Language Toggle */}
          <View style={styles.languageContainer}>
            <TouchableOpacity
              style={[
                styles.languageOption,
                language === 'english' && styles.languageOptionActive,
              ]}
              onPress={() => setLanguage('english')}
            >
              <Text
                style={[
                  styles.languageText,
                  language === 'english' && styles.languageTextActive,
                ]}
              >
                English
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[
                styles.languageOption,
                language === 'romanUrdu' && styles.languageOptionActive,
              ]}
              onPress={() => setLanguage('romanUrdu')}
            >
              <Text
                style={[
                  styles.languageText,
                  language === 'romanUrdu' && styles.languageTextActive,
                ]}
              >
                Roman Urdu
              </Text>
            </TouchableOpacity>
          </View>

          {/* Share/Download Options */}
          <Text style={styles.sectionTitle}>Share or Download</Text>

          <View style={styles.optionsGrid}>
            {/* WhatsApp */}
            <TouchableOpacity
              style={[styles.optionCard, styles.optionCardHighlight]}
              onPress={() => handleExport(onShareWhatsApp, 'WhatsApp')}
              activeOpacity={0.7}
            >
              <View style={[styles.optionIcon, { backgroundColor: '#25D36620' }]}>
                <WhatsappLogoIcon size={28} color="#25D366" weight="fill" />
              </View>
              <Text style={styles.optionTitle}>WhatsApp</Text>
              <Text style={styles.optionSubtitle}>BHEJEIN</Text>
            </TouchableOpacity>

            {/* PDF */}
            <TouchableOpacity
              style={styles.optionCard}
              onPress={() => handleExport(onExportPDF, 'PDF')}
              activeOpacity={0.7}
            >
              <View style={[styles.optionIcon, { backgroundColor: '#E5393520' }]}>
                <FilePdfIcon size={28} color="#E53935" weight="fill" />
              </View>
              <Text style={styles.optionTitle}>PDF Document</Text>
              <Text style={styles.optionSubtitle}>DOWNLOAD</Text>
            </TouchableOpacity>

            {/* Excel */}
            <TouchableOpacity
              style={styles.optionCard}
              onPress={() => handleExport(onExportExcel, 'Excel')}
              activeOpacity={0.7}
            >
              <View style={[styles.optionIcon, { backgroundColor: '#1D6F4220' }]}>
                <FileXlsIcon size={28} color="#1D6F42" weight="fill" />
              </View>
              <Text style={styles.optionTitle}>Excel Sheet</Text>
              <Text style={styles.optionSubtitle}>EXPORT</Text>
            </TouchableOpacity>

            {/* Email */}
            <TouchableOpacity
              style={styles.optionCard}
              onPress={() => handleExport(onShareEmail, 'Email')}
              activeOpacity={0.7}
            >
              <View style={[styles.optionIcon, { backgroundColor: '#1976D220' }]}>
                <EnvelopeIcon size={28} color="#1976D2" weight="fill" />
              </View>
              <Text style={styles.optionTitle}>Email</Text>
              <Text style={styles.optionSubtitle}>SEND</Text>
            </TouchableOpacity>
          </View>

          {/* More Sharing Options */}
          <TouchableOpacity
            style={styles.moreOptionsButton}
            onPress={handleMoreSharing}
            activeOpacity={0.7}
          >
            <ShareNetworkIcon size={20} color={theme.colors.text.primary} />
            <Text style={styles.moreOptionsText}>More Sharing Options</Text>
          </TouchableOpacity>
        </Pressable>
      </Pressable>
    </Modal>
  );
};

const createStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    container: {
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: theme.spacing.xl,
      maxHeight: '90%',
    },
    handleBar: {
      width: 40,
      height: 4,
      backgroundColor: theme.colors.border,
      borderRadius: 2,
      alignSelf: 'center',
      marginTop: theme.spacing.sm,
      marginBottom: theme.spacing.md,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.md,
      marginBottom: theme.spacing.md,
    },
    closeButton: {
      padding: theme.spacing.xs,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.text.primary,
    },
    moreButton: {
      padding: theme.spacing.xs,
    },
    previewCard: {
      flexDirection: 'row',
      backgroundColor: theme.colors.surface,
      marginHorizontal: theme.spacing.md,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    previewInfo: {
      flex: 1,
    },
    previewLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: theme.colors.primary,
      letterSpacing: 0.5,
    },
    previewTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text.primary,
      marginTop: theme.spacing.xs,
    },
    previewDate: {
      fontSize: 13,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
    },
    previewPlaceholder: {
      width: 80,
      justifyContent: 'center',
      gap: theme.spacing.xs,
    },
    previewLine: {
      height: 8,
      backgroundColor: theme.colors.primary,
      borderRadius: 4,
      opacity: 0.3,
    },
    languageContainer: {
      flexDirection: 'row',
      marginHorizontal: theme.spacing.md,
      marginTop: theme.spacing.lg,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
      padding: theme.spacing.xs,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    languageOption: {
      flex: 1,
      paddingVertical: theme.spacing.sm,
      alignItems: 'center',
      borderRadius: theme.borderRadius.sm,
    },
    languageOptionActive: {
      backgroundColor: theme.colors.background,
      ...theme.shadows.sm,
    },
    languageText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.text.secondary,
    },
    languageTextActive: {
      color: theme.colors.text.primary,
      fontWeight: '600',
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.secondary,
      marginHorizontal: theme.spacing.md,
      marginTop: theme.spacing.lg,
      marginBottom: theme.spacing.md,
    },
    optionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    optionCard: {
      width: '48%',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    optionCardHighlight: {
      borderColor: theme.colors.primary,
      backgroundColor: `${theme.colors.primary}05`,
    },
    optionIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: theme.spacing.sm,
    },
    optionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
    },
    optionSubtitle: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.colors.primary,
      marginTop: 2,
      letterSpacing: 0.5,
    },
    moreOptionsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: theme.spacing.md,
      marginTop: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
      gap: theme.spacing.sm,
    },
    moreOptionsText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
    },
  });

export default ExportReportModal;
