import React, { useEffect, useMemo, useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Linking,
  BackHandler,
} from 'react-native';
import { useNavigation, CommonActions } from '@react-navigation/native';
import { SafeAreaView } from 'react-native-safe-area-context';
import {
  CheckCircleIcon,
  PaperPlaneTiltIcon,
  PlusIcon,
  HouseIcon,
  RepeatIcon,
  CalendarIcon,
  FileTextIcon,
} from 'phosphor-react-native';

import {
  useTheme,
  useAppDispatch,
  useAppSelector,
} from '../../../../store/hooks';
import ActionButton from '../../../../components/common/ActionButton';
import {
  selectLastSubmittedEntry,
  selectCurrentEntry,
  selectTotalDebit,
  resetCurrentEntry,
} from '../../../../store/slices/journalEntrySlice';
import Toast from 'react-native-toast-message';

const ConfirmationScreen: React.FC = () => {
  const theme = useTheme();
  const navigation = useNavigation();
  const dispatch = useAppDispatch();

  const lastSubmittedEntry = useAppSelector(selectLastSubmittedEntry);
  const currentEntry = useAppSelector(selectCurrentEntry);
  const totalDebit = useAppSelector(selectTotalDebit);

  const styles = useMemo(() => createStyles(theme), [theme]);

  useEffect(() => {
    const backHandler = BackHandler.addEventListener(
      'hardwareBackPress',
      () => {
        handleDone();
        return true;
      }
    );

    return () => backHandler.remove();
  }, []);

  const formatCurrency = (amount: number) => {
    return `PKR ${amount.toLocaleString()}`;
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return 'Today';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const entryNumber = useMemo(() => {
    if (lastSubmittedEntry?.entryNumber) {
      return `JE-${lastSubmittedEntry.entryNumber}`;
    }
    return `JE-${Date.now().toString().slice(-6)}`;
  }, [lastSubmittedEntry]);

  const entryDate = useMemo(() => {
    return lastSubmittedEntry?.postingDate || currentEntry.postingDate;
  }, [lastSubmittedEntry, currentEntry]);

  const entryAmount = useMemo(() => {
    if (lastSubmittedEntry?.totalDebit) {
      return lastSubmittedEntry.totalDebit;
    }
    return totalDebit;
  }, [lastSubmittedEntry, totalDebit]);

  const lineItemsCount = useMemo(() => {
    if (lastSubmittedEntry?.entries) {
      return lastSubmittedEntry.entries.length;
    }
    return currentEntry.lineItems.filter(
      item => item.accountId > 0 && (item.debit > 0 || item.credit > 0)
    ).length;
  }, [lastSubmittedEntry, currentEntry]);

  const handleDone = useCallback(() => {
    dispatch(resetCurrentEntry());
    navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: 'Home' as never }],
      })
    );
  }, [dispatch, navigation]);

  const handleAddAnother = useCallback(() => {
    dispatch(resetCurrentEntry());
    navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: 'JournalEntryFlow' as never }],
      })
    );
  }, [dispatch, navigation]);

  const handleShareEntry = useCallback(() => {
    const message =
      `📒 Journal Entry Recorded\n\n` +
      `Entry #: ${entryNumber}\n` +
      `Date: ${formatDate(entryDate)}\n` +
      `Amount: ${formatCurrency(entryAmount)}\n` +
      `Line Items: ${lineItemsCount}\n` +
      `${currentEntry.makeRecurring ? '🔄 Recurring Entry\n' : ''}` +
      `${currentEntry.narration ? `\nNarration: ${currentEntry.narration}\n` : ''}` +
      `\nGenerated by HisabKaro`;

    Linking.openURL(
      `whatsapp://send?text=${encodeURIComponent(message)}`
    ).catch(() => {
      Toast.show({
        type: 'error',
        text1: 'WhatsApp Not Found',
        text2: 'Unable to open WhatsApp',
      });
    });
  }, [entryNumber, entryDate, entryAmount, lineItemsCount, currentEntry]);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        {/* Success Header */}
        <View style={styles.successHeader}>
          <View style={styles.successIconContainer}>
            <CheckCircleIcon
              size={64}
              color={theme.colors.success}
              weight="fill"
            />
          </View>
          <Text style={styles.successTitle}>Entry Posted!</Text>
          <Text style={styles.successSubtitle}>
            Journal entry has been recorded successfully / Entry darj ho gayi
          </Text>
        </View>

        {/* Entry Number Card */}
        <View style={styles.entryNumberCard}>
          <Text style={styles.entryLabel}>Entry #</Text>
          <Text style={styles.entryValue}>{entryNumber}</Text>
        </View>

        {/* Summary Card */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryRow}>
            <CalendarIcon size={18} color={theme.colors.text.secondary} />
            <Text style={styles.summaryLabel}>Posting Date</Text>
            <Text style={styles.summaryValue}>{formatDate(entryDate)}</Text>
          </View>

          <View style={styles.summaryRow}>
            <FileTextIcon size={18} color={theme.colors.text.secondary} />
            <Text style={styles.summaryLabel}>Total Amount</Text>
            <Text style={[styles.summaryValue, styles.summaryValueLarge]}>
              {formatCurrency(entryAmount)}
            </Text>
          </View>

          <View style={styles.summaryRow}>
            <FileTextIcon size={18} color={theme.colors.text.secondary} />
            <Text style={styles.summaryLabel}>Line Items</Text>
            <Text style={styles.summaryValue}>
              {lineItemsCount} {lineItemsCount === 1 ? 'entry' : 'entries'}
            </Text>
          </View>

          {currentEntry.referenceNumber && (
            <View style={styles.summaryRow}>
              <FileTextIcon size={18} color={theme.colors.text.secondary} />
              <Text style={styles.summaryLabel}>Reference #</Text>
              <Text style={styles.summaryValue}>{currentEntry.referenceNumber}</Text>
            </View>
          )}

          {currentEntry.makeRecurring && (
            <>
              <View style={styles.divider} />
              <View style={styles.recurringBadge}>
                <RepeatIcon size={16} color={theme.colors.primary} />
                <Text style={styles.recurringText}>
                  Recurring Entry - {currentEntry.recurringOptions?.entryName}
                </Text>
              </View>
              <Text style={styles.recurringSubtext}>
                {currentEntry.recurringOptions?.frequencyType === 'daily' ? 'Daily' :
                 currentEntry.recurringOptions?.frequencyType === 'weekly' ? 'Weekly' :
                 currentEntry.recurringOptions?.frequencyType === 'monthly' ? 'Monthly' :
                 currentEntry.recurringOptions?.frequencyType === 'quarterly' ? 'Quarterly' : 'Yearly'}
                {currentEntry.recurringOptions?.autoPost && ' - Auto Post Enabled'}
              </Text>
            </>
          )}
        </View>

        {/* Actions Section */}
        <Text style={styles.actionsTitle}>What's next? / Aagay kya?</Text>

        <TouchableOpacity
          style={styles.actionCard}
          onPress={handleShareEntry}
          activeOpacity={0.7}
        >
          <View style={[styles.actionIcon, { backgroundColor: '#007AFF15' }]}>
            <PaperPlaneTiltIcon size={24} color="#007AFF" weight="fill" />
          </View>
          <View style={styles.actionContent}>
            <Text style={styles.actionLabel}>Share Entry Details</Text>
            <Text style={styles.actionDescription}>
              Share via WhatsApp / Entry ki tafseel bhaijein
            </Text>
          </View>
        </TouchableOpacity>
      </ScrollView>

      {/* Bottom Actions */}
      <View style={styles.bottomActions}>
        <ActionButton
          title="Done / Mukamal"
          onPress={handleDone}
          variant="primary"
          icon={<HouseIcon size={20} color="#FFFFFF" weight="bold" />}
        />

        <View style={styles.secondaryActions}>
          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={handleAddAnother}
          >
            <PlusIcon size={18} color={theme.colors.text.secondary} />
            <Text style={styles.secondaryButtonText}>
              Add Another Entry / Aur entry karein
            </Text>
          </TouchableOpacity>
        </View>
      </View>
    </SafeAreaView>
  );
};

const createStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      padding: theme.spacing.md,
    },
    successHeader: {
      alignItems: 'center',
      marginBottom: theme.spacing.lg,
    },
    successIconContainer: {
      marginBottom: theme.spacing.sm,
    },
    successTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.colors.text.primary,
      marginTop: theme.spacing.sm,
    },
    successSubtitle: {
      fontSize: 14,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
      textAlign: 'center',
    },
    entryNumberCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.lg,
      alignItems: 'center',
      ...theme.shadows.sm,
    },
    entryLabel: {
      fontSize: 12,
      color: theme.colors.text.secondary,
      marginBottom: theme.spacing.xs,
    },
    entryValue: {
      fontSize: 20,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    summaryCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.lg,
      ...theme.shadows.sm,
    },
    summaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.sm,
    },
    summaryLabel: {
      fontSize: 14,
      color: theme.colors.text.secondary,
      flex: 1,
    },
    summaryValue: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
      textAlign: 'right',
    },
    summaryValueLarge: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.divider,
      marginVertical: theme.spacing.sm,
    },
    recurringBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      backgroundColor: `${theme.colors.primary}10`,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.borderRadius.md,
    },
    recurringText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.primary,
    },
    recurringSubtext: {
      fontSize: 12,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
      marginLeft: theme.spacing.md,
    },
    actionsTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.text.primary,
      marginBottom: theme.spacing.md,
    },
    actionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.sm,
      ...theme.shadows.sm,
    },
    actionIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing.md,
    },
    actionContent: {
      flex: 1,
    },
    actionLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
      marginBottom: 2,
    },
    actionDescription: {
      fontSize: 12,
      color: theme.colors.text.secondary,
    },
    bottomActions: {
      padding: theme.spacing.md,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      gap: theme.spacing.sm,
    },
    secondaryActions: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    secondaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.xs,
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.borderRadius.md,
      paddingVertical: theme.spacing.sm,
    },
    secondaryButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.text.secondary,
    },
  });

export default ConfirmationScreen;
