import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  RefreshControl,
  ActivityIndicator,
  Share,
} from 'react-native';
import {
  CaretLeftIcon,
  TranslateIcon,
  SparkleIcon,
  FilePdfIcon,
  WhatsappLogoIcon,
  TruckIcon,
} from 'phosphor-react-native';
import Toast from 'react-native-toast-message';
import { NavigationProps } from '../../types';
import { Container } from '../../components/common';
import { useTheme } from '../../store/hooks';
import { suppliersApi, Supplier, SupplierStatement } from '../../services/api';

type FilterPeriod = 'today' | 'this_week' | 'last_30_days' | 'all';

const SupplierLedgerScreen: React.FC<NavigationProps<'SupplierLedger'>> = ({ 
  navigation, 
  route 
}) => {
  const theme = useTheme();
  const { supplierId, supplierName } = route.params || {};
  
  const [supplier, setSupplier] = useState<Supplier | null>(null);
  const [statements, setStatements] = useState<SupplierStatement[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [filterPeriod, setFilterPeriod] = useState<FilterPeriod>('last_30_days');
  const [isUrdu, setIsUrdu] = useState(false);

  const styles = useMemo(() => createStyles(theme), [theme]);

  // Calculate date range based on filter
  const getDateRange = useCallback((period: FilterPeriod): { startDate?: string; endDate?: string } => {
    const today = new Date();
    const endDate = today.toISOString().split('T')[0];
    
    switch (period) {
      case 'today':
        return { startDate: endDate, endDate };
      case 'this_week': {
        const weekStart = new Date(today);
        weekStart.setDate(today.getDate() - today.getDay());
        return { startDate: weekStart.toISOString().split('T')[0], endDate };
      }
      case 'last_30_days': {
        const monthStart = new Date(today);
        monthStart.setDate(today.getDate() - 30);
        return { startDate: monthStart.toISOString().split('T')[0], endDate };
      }
      default:
        return {};
    }
  }, []);

  // Fetch data
  const fetchData = useCallback(async (isRefresh: boolean = false) => {
    if (!supplierId) return;
    
    try {
      if (!isRefresh) setLoading(true);
      
      const { startDate, endDate } = getDateRange(filterPeriod);
      
      const [supplierData, statementData] = await Promise.all([
        suppliersApi.getById(supplierId),
        suppliersApi.getStatement(supplierId, startDate, endDate),
      ]);
      
      setSupplier(supplierData);
      setStatements(statementData);
    } catch (error: any) {
      Toast.show({
        type: 'error',
        text1: 'Error',
        text2: error.message || 'Failed to load ledger',
      });
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [supplierId, filterPeriod, getDateRange]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Handle refresh
  const handleRefresh = () => {
    setRefreshing(true);
    fetchData(true);
  };

  // Format currency
  const formatCurrency = (amount: number): string => {
    if (amount === 0) return '—';
    return amount.toLocaleString();
  };

  // Format date
  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-PK', {
      day: '2-digit',
      month: 'short',
    });
  };

  // Toggle language
  const toggleLanguage = () => {
    setIsUrdu(!isUrdu);
  };

  // Handle PDF export
  const handlePdfExport = () => {
    Toast.show({
      type: 'info',
      text1: 'PDF Export',
      text2: 'Generating PDF ledger...',
    });
    // TODO: Implement PDF generation
  };

  // Handle WhatsApp share
  const handleWhatsAppShare = async () => {
    try {
      const message = `📒 Khata - ${supplierName}\n\n` +
        `Payable Balance: Rs. ${supplier?.payable_balance?.toLocaleString() || 0}\n` +
        `Total Purchases: Rs. ${supplier?.total_purchases?.toLocaleString() || 0}\n` +
        `Total Payments: Rs. ${supplier?.total_payments?.toLocaleString() || 0}\n\n` +
        `Generated by HisabKaro`;
      
      await Share.share({
        message,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  // Get period label
  const getPeriodLabel = (period: FilterPeriod): string => {
    const labels: Record<FilterPeriod, string> = {
      today: 'Today',
      this_week: 'This Week',
      last_30_days: 'Last 30 Days',
      all: 'All Time',
    };
    return labels[period];
  };

  if (loading) {
    return (
      <Container safeArea edges={['top']}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={theme.colors.primary} />
          <Text style={styles.loadingText}>Loading ledger...</Text>
        </View>
      </Container>
    );
  }

  return (
    <Container safeArea edges={['top']}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.headerButton}
          onPress={() => navigation.goBack()}
        >
          <CaretLeftIcon size={24} color={theme.colors.text.primary} />
        </TouchableOpacity>
        
        <Text style={styles.headerTitle}>Supplier Ledger</Text>
        
        <TouchableOpacity 
          style={[styles.headerButton, styles.translateButton]}
          onPress={toggleLanguage}
        >
          <TranslateIcon size={20} color="#fff" weight="fill" />
        </TouchableOpacity>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={handleRefresh}
            tintColor={theme.colors.primary}
            colors={[theme.colors.primary]}
          />
        }
      >
        {/* Supplier Profile */}
        <View style={styles.profileSection}>
          <View style={styles.avatarContainer}>
            <View style={styles.avatarPlaceholder}>
              <TruckIcon size={32} color={theme.colors.warning} weight="fill" />
            </View>
            <View style={styles.statusDot} />
          </View>
          
          <Text style={styles.supplierName}>{supplierName}</Text>
          <Text style={[
            styles.balanceAmount,
            (supplier?.payable_balance || 0) > 0 ? styles.balanceOrange : styles.balanceGreen
          ]}>
            Rs. {supplier?.payable_balance?.toLocaleString() || 0}
          </Text>
          <Text style={styles.balanceLabel}>
            {isUrdu ? 'دینا باقی' : 'DENA BAAQI (PAYABLE)'}
          </Text>
        </View>

        {/* Period Filter */}
        <View style={styles.filterContainer}>
          {(['today', 'this_week', 'last_30_days'] as FilterPeriod[]).map((period) => (
            <TouchableOpacity
              key={period}
              style={[
                styles.filterTab,
                filterPeriod === period && styles.filterTabActive
              ]}
              onPress={() => setFilterPeriod(period)}
            >
              <Text style={[
                styles.filterTabText,
                filterPeriod === period && styles.filterTabTextActive
              ]}>
                {getPeriodLabel(period)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Ledger Table */}
        <View style={styles.tableContainer}>
          {/* Table Header */}
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderText, styles.colDate]}>
              {isUrdu ? 'تاریخ/تفصیل' : 'DATE / DETAIL'}
            </Text>
            <Text style={[styles.tableHeaderText, styles.colDebit]}>
              {isUrdu ? 'خریداری' : 'IN (DR)'}
            </Text>
            <Text style={[styles.tableHeaderText, styles.colCredit]}>
              {isUrdu ? 'ادائیگی' : 'OUT (CR)'}
            </Text>
            <Text style={[styles.tableHeaderText, styles.colBalance]}>
              {isUrdu ? 'بقایا' : 'BAL'}
            </Text>
          </View>

          {/* Table Rows */}
          {statements.length === 0 ? (
            <View style={styles.emptyTable}>
              <Text style={styles.emptyTableText}>
                {isUrdu ? 'کوئی لین دین نہیں' : 'No transactions found'}
              </Text>
            </View>
          ) : (
            statements.map((item, index) => (
              <View key={item.id || index} style={styles.tableRow}>
                <View style={styles.colDate}>
                  <Text style={styles.rowDate}>{formatDate(item.date)}</Text>
                  <Text style={styles.rowDetail} numberOfLines={1}>
                    {item.description}
                  </Text>
                </View>
                <Text style={[
                  styles.rowAmount, 
                  styles.colDebit,
                  item.debit > 0 && styles.amountOrange
                ]}>
                  {formatCurrency(item.debit)}
                </Text>
                <Text style={[
                  styles.rowAmount, 
                  styles.colCredit,
                  item.credit > 0 && styles.amountGreen
                ]}>
                  {formatCurrency(item.credit)}
                </Text>
                <Text style={[styles.rowAmount, styles.colBalance]}>
                  {item.balance.toLocaleString()}
                </Text>
              </View>
            ))
          )}

          {/* Opening Balance Row */}
          {statements.length > 0 && (
            <View style={[styles.tableRow, styles.openingBalanceRow]}>
              <View style={styles.colDate}>
                <Text style={styles.rowDate}>—</Text>
                <Text style={styles.rowDetail}>{isUrdu ? 'پچھلا بقایا' : 'Previous Bal'}</Text>
              </View>
              <Text style={[styles.rowAmount, styles.colDebit]}>—</Text>
              <Text style={[styles.rowAmount, styles.colCredit]}>—</Text>
              <Text style={[styles.rowAmount, styles.colBalance]}>0</Text>
            </View>
          )}
        </View>

        {/* AI Button */}
        <TouchableOpacity style={styles.aiButton}>
          <SparkleIcon size={20} color="#fff" weight="fill" />
        </TouchableOpacity>
      </ScrollView>

      {/* Bottom Actions */}
      <View style={styles.bottomActions}>
        <TouchableOpacity style={styles.pdfButton} onPress={handlePdfExport}>
          <FilePdfIcon size={20} color={theme.colors.text.primary} />
          <Text style={styles.pdfButtonText}>PDF Ledger</Text>
        </TouchableOpacity>
        
        <TouchableOpacity style={styles.whatsappButton} onPress={handleWhatsAppShare}>
          <WhatsappLogoIcon size={20} color="#fff" weight="fill" />
          <Text style={styles.whatsappButtonText}>WhatsApp</Text>
        </TouchableOpacity>
      </View>
    </Container>
  );
};

const createStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    headerButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.text.primary,
    },
    translateButton: {
      backgroundColor: theme.colors.warning,
      borderRadius: theme.borderRadius.lg,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 100,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      ...theme.typography.body,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.md,
    },
    profileSection: {
      alignItems: 'center',
      paddingVertical: theme.spacing.xl,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: theme.spacing.md,
    },
    avatarPlaceholder: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: `${theme.colors.warning}20`,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: theme.colors.warning,
    },
    statusDot: {
      position: 'absolute',
      bottom: 4,
      right: 4,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.warning,
      borderWidth: 2,
      borderColor: theme.colors.background,
    },
    supplierName: {
      fontSize: 22,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
      marginBottom: theme.spacing.xs,
    },
    balanceAmount: {
      fontSize: 28,
      fontWeight: 'bold',
    },
    balanceOrange: {
      color: theme.colors.warning,
    },
    balanceGreen: {
      color: theme.colors.success,
    },
    balanceLabel: {
      fontSize: 11,
      color: theme.colors.text.secondary,
      marginTop: 4,
      letterSpacing: 0.5,
    },
    filterContainer: {
      flexDirection: 'row',
      paddingHorizontal: theme.spacing.md,
      marginBottom: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    filterTab: {
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.borderRadius.full,
      backgroundColor: theme.colors.surface,
    },
    filterTabActive: {
      backgroundColor: theme.colors.warning,
    },
    filterTabText: {
      fontSize: 13,
      color: theme.colors.text.secondary,
      fontWeight: '500',
    },
    filterTabTextActive: {
      color: '#fff',
    },
    tableContainer: {
      marginHorizontal: theme.spacing.md,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.lg,
      overflow: 'hidden',
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: `${theme.colors.text.disabled}20`,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
    },
    tableHeaderText: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.colors.text.secondary,
      letterSpacing: 0.5,
    },
    colDate: {
      flex: 2,
    },
    colDebit: {
      flex: 1,
      textAlign: 'center',
    },
    colCredit: {
      flex: 1,
      textAlign: 'center',
    },
    colBalance: {
      flex: 1,
      textAlign: 'right',
    },
    tableRow: {
      flexDirection: 'row',
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      alignItems: 'center',
    },
    openingBalanceRow: {
      backgroundColor: `${theme.colors.text.disabled}10`,
    },
    rowDate: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
    },
    rowDetail: {
      fontSize: 11,
      color: theme.colors.text.secondary,
      marginTop: 2,
    },
    rowAmount: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.text.primary,
    },
    amountOrange: {
      color: theme.colors.warning,
    },
    amountGreen: {
      color: theme.colors.success,
    },
    emptyTable: {
      paddingVertical: theme.spacing.xl,
      alignItems: 'center',
    },
    emptyTableText: {
      fontSize: 14,
      color: theme.colors.text.secondary,
    },
    aiButton: {
      position: 'absolute',
      bottom: theme.spacing.xl,
      right: theme.spacing.md,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.warning,
      alignItems: 'center',
      justifyContent: 'center',
      ...theme.shadows.lg,
    },
    bottomActions: {
      flexDirection: 'row',
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.md,
      paddingBottom: theme.spacing.lg,
      gap: theme.spacing.md,
      backgroundColor: theme.colors.background,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    pdfButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
      paddingVertical: theme.spacing.md,
      borderRadius: theme.borderRadius.lg,
      gap: theme.spacing.sm,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    pdfButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.primary,
    },
    whatsappButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#25D366',
      paddingVertical: theme.spacing.md,
      borderRadius: theme.borderRadius.lg,
      gap: theme.spacing.sm,
    },
    whatsappButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#fff',
    },
  });

export default SupplierLedgerScreen;
